export const heroClasses = {
  Mage: {
    name: 'Mage',
    description: 'Masters of the arcane arts, specializing in Mathematics. Unlocks proof spells and equation combos.',
    subject: 'Mathematics',
    skills: {},
  },
  Engineer: {
    name: 'Engineer',
    description: 'Builders and innovators, specializing in Programming. Unlocks refactor bursts and debug shields.',
    subject: 'Programming',
    skills: {},
  },
  Scientist: {
    name: 'Scientist',
    description: 'Explorers of the natural world, specializing in Physics and Data Science. Unlocks experiment surges.',
    subject: 'Physics',
    skills: {},
  },
  Alchemist: {
    name: 'Alchemist',
    description: 'Masters of chemical reactions and potions, specializing in Chemistry.',
    subject: 'Chemistry',
    skills: {},
  },
  Historian: {
    name: 'Historian',
    description: 'Keepers of lore and time, specializing in History. Unlocks timeline visions.',
    subject: 'History',
    skills: {},
  },
  Bard: {
    name: 'Bard',
    description: 'Storytellers and artists, specializing in Literature. Unlocks inspiration anthems.',
    subject: 'Literature',
    skills: {},
  },
  Warrior: {
    name: 'Warrior',
    description: 'Strategic fighters specializing in Logic and PE challenges.',
    subject: 'Logic',
    skills: {},
  },
  Druid: {
    name: 'Druid',
    description: 'Nature guardians specializing in Biology and ecology.',
    subject: 'Biology',
    skills: {},
  },
};

export const questions = {
  Mathematics: {
    easy: [
      { id: 'm_e_1', question: 'What is 2 + 2?', answer: '4', category: 'arithmetic' },
      { id: 'm_e_2', question: 'What is 10 - 3?', answer: '7', category: 'arithmetic' },
      { id: 'm_e_3', question: 'What is 4 * 5?', answer: '20', category: 'arithmetic' },
      { id: 'm_e_4', question: 'What is 12 / 3?', answer: '4', category: 'arithmetic' },
      { id: 'm_e_5', question: 'What is 15 % 4?', answer: '3', category: 'arithmetic' },
      { id: 'm_e_6', question: 'What is the value of 100?', answer: '100', category: 'numbers' },
      { id: 'm_e_7', question: 'Is 5 odd or even?', answer: 'odd', category: 'properties' },
      { id: 'm_e_8', question: 'What is 0 + 0?', answer: '0', category: 'arithmetic' },
    ],
    medium: [
      { id: 'm_m_1', question: 'Solve for x: 2x + 3 = 11', answer: '4', category: 'algebra' },
      { id: 'm_m_2', question: 'What is 25% of 80?', answer: '20', category: 'percentages' },
      { id: 'm_m_3', question: 'Simplify: 2 + 3 * 4', answer: '14', category: 'order' },
      { id: 'm_m_4', question: 'Solve: x/5 = 6', answer: '30', category: 'algebra' },
      { id: 'm_m_5', question: 'What is the area of rectangle 5x7?', answer: '35', category: 'geometry' },
      { id: 'm_m_6', question: 'What is √16?', answer: '4', category: 'roots' },
      { id: 'm_m_7', question: 'Convert 0.75 to fraction?', answer: '3/4', category: 'fractions' },
      { id: 'm_m_8', question: 'Solve: |x - 3| = 5', answer: '8 or -2', category: 'absolute' },
    ],
    hard: [
      { id: 'm_h_1', question: 'What is the derivative of x^2?', answer: '2x', category: 'calculus' },
      { id: 'm_h_2', question: 'Expand (x + 2)^2?', answer: 'x^2 + 4x + 4', category: 'binomial' },
      { id: 'm_h_3', question: 'Log10(100) = ?', answer: '2', category: 'logarithms' },
      { id: 'm_h_4', question: 'Sin(90°) = ?', answer: '1', category: 'trigonometry' },
      { id: 'm_h_5', question: 'Integral of 2x dx?', answer: 'x^2 + C', category: 'calculus' },
      { id: 'm_h_6', question: 'Solve quadratic x^2 - 5x + 6 = 0?', answer: '2, 3', category: 'quadratics' },
      { id: 'm_h_7', question: 'Limit x->0 sinx/x?', answer: '1', category: 'limits' },
      { id: 'm_h_8', question: 'Taylor for e^x at 0, first 3?', answer: '1 + x + x^2/2', category: 'series' },
    ],
  },
  Programming: {
    easy: [
      { id: 'p_e_1', question: 'What does HTML stand for?', answer: 'HyperText Markup Language' },
      { id: 'p_e_2', question: 'What tag starts HTML?', answer: '<html>' },
      { id: 'p_e_3', question: 'CSS stands for?', answer: 'Cascading Style Sheets' },
      { id: 'p_e_4', question: 'JS for JavaScript?', answer: 'Yes' },
      { id: 'p_e_5', question: 'What does console.log do?', answer: 'Print to console' },
      { id: 'p_e_6', question: 'Array [1,2].length?', answer: '2' },
      { id: 'p_e_7', question: '"hello".length?', answer: '5' },
      { id: 'p_e_8', question: 'function name(){} call?', answer: 'name()' },
    ],
    medium: [
      { id: 'p_m_1', question: 'What is a closure?', answer: 'Function accessing outer scope' },
      { id: 'p_m_2', question: 'Difference let/const/var?', answer: 'Scope/hoist/reassign' },
      { id: 'p_m_3', question: 'async/await does?', answer: 'Handle promises' },
      { id: 'p_m_4', question: 'Map vs forEach?', answer: 'Returns array vs void' },
      { id: 'p_m_5', question: 'What is hoisting?', answer: 'Decl moved top' },
      { id: 'p_m_6', question: '== vs ===?', answer: 'Type coerce vs strict' },
      { id: 'p_m_7', question: 'Promise.all does?', answer: 'All resolve' },
      { id: 'p_m_8', question: 'Event loop purpose?', answer: 'Async tasks' },
    ],
    hard: [
      { id: 'p_h_1', question: 'Prototype inheritance?', answer: '.__proto__ chain' },
      { id: 'p_h_2', question: 'What is currying?', answer: 'Partial apply functions' },
      { id: 'p_h_3', question: 'WeakMap use?', answer: 'GC no prevent' },
      { id: 'p_h_4', question: 'Microtasks vs macrotasks?', answer: 'Promise vs setTimeout' },
      { id: 'p_h_5', question: 'this in arrow?', answer: 'Lexical' },
      { id: 'p_h_6', question: 'Memoization technique?', answer: 'Cache results' },
      { id: 'p_h_7', question: 'Proxy object for?', answer: 'Meta programming' },
      { id: 'p_h_8', question: 'Generator yield?', answer: 'Pause/resume' },
    ],
  },
  Physics: {
    easy: [
      { id: 'ph_e_1', question: 'Speed = distance/time?', answer: 'Yes' },
      { id: 'ph_e_2', question: 'Acceleration unit?', answer: 'm/s²' },
      { id: 'ph_e_3', question: 'Force = mass * acceleration?', answer: 'Newton\'s 2nd' },
      { id: 'ph_e_4', question: 'Gravity on Earth?', answer: '9.8 m/s²' },
      { id: 'ph_e_5', question: 'Energy conserved?', answer: 'Yes' },
      { id: 'ph_e_6', question: 'Work = force * distance?', answer: 'Yes' },
      { id: 'ph_e_7', question: 'Momentum p = ?', answer: 'mv' },
      { id: 'ph_e_8', question: 'Wavelength symbol?', answer: 'λ' },
    ],
    medium: [
      { id: 'ph_m_1', question: 'v = u + at formula?', answer: 'Yes' },
      { id: 'ph_m_2', question: 'Kinetic E = 1/2 mv^2?', answer: 'Yes' },
      { id: 'ph_m_3', question: 'Ohm\'s law?', answer: 'V=IR' },
      { id: 'ph_m_4', question: 'Power P = ?', answer: 'VI' },
      { id: 'ph_m_5', question: 'Frequency f = 1/T?', answer: 'Yes' },
      { id: 'ph_m_6', question: 'Refractive index n >1?', answer: 'Slower light' },
      { id: 'ph_m_7', question: 'Newton\'s 3rd law?', answer: 'Action reaction' },
      { id: 'ph_m_8', question: 'E=mc² meaning?', answer: 'Mass energy' },
    ],
    hard: [
      { id: 'ph_h_1', question: 'Schrodinger equation?', answer: 'Wave function' },
      { id: 'ph_h_2', question: 'Uncertainty principle?', answer: 'Δx Δp ≥ ħ/2' },
      { id: 'ph_h_3', question: 'Maxwell equations count?', answer: '4' },
      { id: 'ph_h_4', question: 'Black body radiation?', answer: 'Planck' },
      { id: 'ph_h_5', question: 'Special relativity postulate?', answer: 'Light speed constant' },
      { id: 'ph_h_6', question: 'Photoelectric effect?', answer: 'Einstein' },
      { id: 'ph_h_7', question: 'Angular momentum?', answer: 'L = Iω' },
      { id: 'ph_h_8', question: 'Standard model particles?', answer: 'Quarks leptons bosons' },
    ],
  },
  // Chemistry
  Chemistry: {
    easy: [
      { id: 'c_e_1', question: 'H2O is?', answer: 'Water' },
      { id: 'c_e_2', question: 'NaCl table salt?', answer: 'Yes' },
      { id: 'c_e_3', question: 'Atomic number H?', answer: '1' },
      { id: 'c_e_4', question: 'O2 gas?', answer: 'Oxygen' },
      { id: 'c_e_5', question: 'pH 7 neutral?', answer: 'Yes' },
      { id: 'c_e_6', question: 'CO2 greenhouse?', answer: 'Yes' },
      { id: 'c_e_7', question: 'Gold symbol?', answer: 'Au' },
      { id: 'c_e_8', question: 'Acid + base?', answer: 'Salt water' },
    ],
    medium: [
      { id: 'c_m_1', question: 'Periodic table rows?', answer: 'Periods' },
      { id: 'c_m_2', question: 'Covalent bond?', answer: 'Share electrons' },
      { id: 'c_m_3', question: 'Mole 6.02e23?', answer: 'Avogadro' },
      { id: 'c_m_4', question: 'pH <7 acid?', answer: 'Yes' },
      { id: 'c_m_5', question: 'Isotope same protons?', answer: 'Different neutrons' },
      { id: 'c_m_6', question: 'Redox oxidation?', answer: 'Lose electrons' },
      { id: 'c_m_7', question: 'Ideal gas PV=nRT?', answer: 'Yes' },
      { id: 'c_m_8', question: 'Organic carbon?', answer: 'Yes' },
    ],
    hard: [
      { id: 'c_h_1', question: 'Quantum number 4?', answer: 'Spin orbital magnetic principal' },
      { id: 'c_h_2', question: 'Le Chatelier principle?', answer: 'Equilibrium shift' },
      { id: 'c_h_3', question: 'Thermodynamics 2nd?', answer: 'Entropy increases' },
      { id: 'c_h_4', question: 'Hybridization sp3?', answer: 'Tetrahedral' },
      { id: 'c_h_5', question: 'Rate law?', answer: 'k [A]^m [B]^n' },
      { id: 'c_h_6', question: 'NMR proton?', answer: 'H nuclei' },
      { id: 'c_h_7', question: 'Electronegativity F?', answer: 'Highest' },
      { id: 'c_h_8', question: 'Gibbs free G = H - TS?', answer: 'Yes' },
    ],
  },
  // History
  History: {
    easy: [
      { id: 'h_e_1', question: 'World War II 1939?', answer: 'Yes' },
      { id: 'h_e_2', question: 'USA independence 1776?', answer: 'Yes' },
      { id: 'h_e_3', question: 'Pyramids Egypt?', answer: 'Yes' },
      { id: 'h_e_4', question: 'Columbus 1492?', answer: 'America' },
      { id: 'h_e_5', question: 'Moon landing 1969?', answer: 'Apollo' },
      { id: 'h_e_6', question: 'Fall Berlin Wall?', answer: '1989' },
      { id: 'h_e_7', question: 'Renaissance Italy?', answer: 'Yes' },
      { id: 'h_e_8', question: 'WW1 cause?', answer: 'Archduke assassination' },
    ],
    medium: [
      { id: 'h_m_1', question: 'Magna Carta 1215?', answer: 'King John' },
      { id: 'h_m_2', question: 'French Revolution?', answer: '1789' },
      { id: 'h_m_3', question: 'Industrial Revolution?', answer: 'Steam power' },
      { id: 'h_m_4', question: 'Cold War?', answer: 'USSR USA' },
      { id: 'h_m_5', question: 'Treaty of Versailles?', answer: 'WW1 end' },
      { id: 'h_m_6', question: 'Roman Empire fall?', answer: '476 AD' },
      { id: 'h_m_7', question: 'American Civil War?', answer: '1861-65' },
      { id: 'h_m_8', question: 'Enlightenment thinker?', answer: 'Voltaire Locke' },
    ],
    hard: [
      { id: 'h_h_1', question: 'Code of Hammurabi?', answer: 'Babylon' },
      { id: 'h_h_2', question: 'Pax Romana?', answer: 'Augustus peace' },
      { id: 'h_h_3', question: 'Mongol Empire?', answer: 'Genghis' },
      { id: 'h_h_4', question: 'Protestant Reformation?', answer: 'Luther 1517' },
      { id: 'h_h_5', question: 'Treaty Westphalia?', answer: '1648 30 years war' },
      { id: 'h_h_6', question: 'Opium Wars?', answer: 'Britain China' },
      { id: 'h_h_7', question: 'Schlieffen Plan?', answer: 'WW1 Germany' },
      { id: 'h_h_8', question: 'Yalta Conference?', answer: '1945 WW2' },
    ],
  },
  // Add more subjects...
  Biology: {
    easy: [
      { id: 'b_e_1', question: 'DNA full form?', answer: 'Deoxyribonucleic Acid' },
      { id: 'b_e_2', question: 'Photosynthesis plant?', answer: 'Yes' },
      { id: 'b_e_3', question: 'Heart chambers?', answer: '4' },
      { id: 'b_e_4', question: 'Blood red cells?', answer: 'RBC' },
      { id: 'b_e_5', question: 'Cell powerhouse?', answer: 'Mitochondria' },
      { id: 'b_e_6', question: 'Human chromosomes?', answer: '46' },
      { id: 'b_e_7', question: 'Evolution Darwin?', answer: 'Yes' },
      { id: 'b_e_8', question: 'Virus living?', answer: 'No' },
    ],
    medium: [
      { id: 'b_m_1', question: 'Mitosis phases?', answer: 'Prophase metaphase anaphase telophase' },
      { id: 'b_m_2', question: 'Meiosis halves?', answer: 'Chromosomes' },
      { id: 'b_m_3', question: 'Punnett square?', answer: 'Genetics' },
      { id: 'b_m_4', question: 'Ecosystem levels?', answer: 'Producer consumer decomposer' },
      { id: 'b_m_5', question: 'Enzyme substrate?', answer: 'Lock key' },
      { id: 'b_m_6', question: 'DNA bases?', answer: 'A T G C' },
      { id: 'b_m_7', question: 'Natural selection?', answer: 'Survival fittest' },
      { id: 'b_m_8', question: 'RNA messenger?', answer: 'mRNA' },
    ],
    hard: [
      { id: 'b_h_1', question: 'Central Dogma?', answer: 'DNA RNA protein' },
      { id: 'b_h_2', question: 'CRISPR?', answer: 'Gene editing' },
      { id: 'b_h_3', question: 'Krebs cycle?', answer: 'Citric acid' },
      { id: 'b_h_4', question: 'Action potential?', answer: 'Neuron fire' },
      { id: 'b_h_5', question: 'Hardy Weinberg?', answer: 'p² + 2pq + q² = 1' },
      { id: 'b_h_6', question: 'Symbiosis types?', answer: 'Mutualism commensalism parasitism' },
      { id: 'b_h_7', question: 'Operon lac?', answer: 'Gene regulation' },
      { id: 'b_h_8', question: 'Phylogenetic tree?', answer: 'Evolution relationships' },
    ],
  },
  // Logic
  Logic: {
    easy: [
      { id: 'l_e_1', question: 'All A B, all B C, A C?', answer: 'Yes syllogism' },
      { id: 'l_e_2', question: 'If P then Q, P true, Q?', answer: 'True modus ponens' },
      { id: 'l_e_3', question: 'Red herring fallacy?', answer: 'Distraction' },
      { id: 'l_e_4', question: 'Ad hominem?', answer: 'Attack person' },
      { id: 'l_e_5', question: 'True or false A and B both?', answer: 'Both true' },
      { id: 'l_e_6', question: 'OR true if?', answer: 'At least one' },
      { id: 'l_e_7', question: 'NOT false true?', answer: 'True' },
      { id: 'l_e_8', question: 'Premise conclusion?', answer: 'Deduction' },
    ],
    medium: [
      { id: 'l_m_1', question: 'Bayes theorem?', answer: 'P(A|B) = P(B|A)P(A)/P(B)' },
      { id: 'l_m_2', question: 'Fallacy slippery slope?', answer: 'Exaggerate chain' },
      { id: 'l_m_3', question: 'Truth table AND?', answer: 'TT T FF F' },
      { id: 'l_m_4', question: 'Valid argument?', answer: 'Premise true imply conclusion' },
      { id: 'l_m_5', question: 'Inductive reasoning?', answer: 'General from specific' },
      { id: 'l_m_6', question: 'Contrapositive?', answer: '~Q -> ~P' },
      { id: 'l_m_7', question: 'Circular reasoning?', answer: 'Beg question' },
      { id: 'l_m_8', question: 'Occam razor?', answer: 'Simplest explanation' },
    ],
    hard: [
      { id: 'l_h_1', question: 'Gödel incompleteness?', answer: 'Formal systems' },
      { id: 'l_h_2', question: 'Turing halting?', answer: 'Undecidable' },
      { id: 'l_h_3', question: 'Russell paradox?', answer: 'Set theory' },
      { id: 'l_h_4', question: 'Modal logic box?', answer: 'Necessarily' },
      { id: 'l_h_5', question: 'Quantifiers ∀∃?', answer: 'All exists' },
      { id: 'l_h_6', question: 'Curry-Howard?', answer: 'Logic proofs programs' },
      { id: 'l_h_7', question: 'Liar paradox?', answer: 'This false' },
      { id: 'l_h_8', question: 'Non-monotonic?', answer: 'Default reasoning' },
    ],
  },
};

export function getQuestion(subject, difficulty) {
  const questionList = questions[subject]?.[difficulty];
  if (!questionList || questionList.length === 0) {
    return { id: 'fallback', question: 'No questions available for this category. Progress to unlock!', answer: '' };
  }
  return questionList[Math.floor(Math.random() * questionList.length)];
}

